### ISSUE TITLE
function output problems

### ISSUE THREAD

**Issue by schochastics** [q1cui/discourseGT#2]
`summaryNet()`

Don display the whole 
` ---------DISCLAIMER AND WARRANTY OF PROVIDED RESULTS AND CODE---------`
part. You can put that into the code as a comment

`plotNGTData`

There are a whole lot of warnings when running the function
```r
#>$episodes_plot
#> Use of `eps_st$episode_length` is discouraged.
#>ℹ Use `episode_length` instead.
#>Warning: Use of `eps_st$Freq` is discouraged.
#>ℹ Use `Freq` instead.
#> $ntr_plot
#> Warning: Use of `temp_plot$participant` is discouraged.
#> ℹ Use `participant` instead.
#> Warning: Use of `temp_plot$normalized_turn_ratio` is discouraged.
#> ℹ Use `normalized_turn_ratio` instead.
#> Warning: Use of `temp_plot$group` is discouraged.
#> ℹ Use `group` instead.
#> Use of `temp_plot$group` is discouraged.
#> ℹ Use `group` instead.
#> Warning: Use of `temp_plot$participant` is discouraged.
#> ℹ Use `participant` instead.
#> Warning: Use of `temp_plot$normalized_turn_ratio` is discouraged.
#> ℹ Use `normalized_turn_ratio` instead.
#> Warning: Use of `temp_plot$group` is discouraged.
#> ℹ Use `group` instead.
#> Use of `temp_plot$group` is discouraged.
#> ℹ Use `group` instead.
```

This is part of the review for JOSS https://github.com/openjournals/joss-reviews/issues/5143

**Comment by q1cui** [comment]
We have fixed plotNGTData(), it is free of warnings in Github. 
We also fixed summaryNet(), ----DISCLAIMER AND WARRANTY OF PROVIDED RESULTS AND CODE---- is not included in the output.

**Comment by q1cui** [comment]
We tested these functions by devtools::install_github("q1cui/discourseGT") for now.
