### ISSUE TITLE
improve pkg docs

### ISSUE THREAD

**Issue by schochastics** [q1cui/discourseGT#5]
?discourseGT is too short. A description of the key functions would be helpful to have here

This is part of the review for JOSS https://github.com/openjournals/joss-reviews/issues/5143

**Comment by q1cui** [comment]
Thanks for pointing it out. We have added a description of the workflow, key functions, and examples. If you click the hyperlink under _how to use_ in README.md, you could see the descriptions.

**Comment by schochastics** [comment]
Thank you. could you link this in the file below
https://github.com/q1cui/discourseGT/blob/d0b1fbbc2230579797652a9fb3afd8b0ea703903/R/discourseGT.R#L1

As a reference, see for instance
```r
library(dplyr)
?dplyr
```

**Comment by q1cui** [comment]
Sure! Thank you again for your fast reply.

**Comment by q1cui** [comment]
Thank you for your comments. We have added key function descriptions to this file: discourseGT/R/discourseGR.R
