### ISSUE TITLE
function parameters

### ISSUE THREAD

**Issue by schochastics** [q1cui/discourseGT#6]
The use of `iscsvfile = TRUE` to indicate that the first parameter is supposed to be interpreted as  path is a bit redundant.
Better check in the function if the input is a character (hence a path to a file) or a data frame.

This is not a mandatory fix for the review, just a suggestion to make the package follow good practices

This is part of the review for JOSS https://github.com/openjournals/joss-reviews/issues/5143

**Comment by q1cui** [comment]
The parameter `iscsvfile = TRUE` is used to help differentiate the two possible input types for `input_file` as you mentioned: path to CSV file(character) or a loaded R data frame. It is used as a protection to ensure that users are aware of the input being passed into the function. 

My understanding of your suggestion is to check the input type within the function itself, a sample modification is copied below, please correct me if this is not what you were suggesting.

edgelist_raw <- function(input_file) {
  
  # check input type, read external input file into data.frame
  if (is.data.frame(input_file)) {
    df <- input_file
  } else if (is.character(input_file)) {
    df <- read.csv(input_file)
  } else {
    warning("Invalid input type. Please input file path as character or input data.frame directly.")
  }

  \# rest of the code
  \```
}

**Comment by schochastics** [comment]
There are two ways to approach this. Yours is ok but you should do a check if the file actually exists
```r
edgelist_raw <- function(input_file) {
  if (is.data.frame(input_file)) {
     df <- input_file
  } else if (is.character(input_file)) {
     if(isFALSE(file.exists(input_file)){
       stop("file not found")
     }
     df <- read.csv(input_file)
  } else {
     warning("Invalid input type. Please input file path as character or input data.frame directly.")
  }
}
```

For future iterations you can also think about including a generic function

```r
edgelist_raw <- function(x) {
    UseMethod("edgelist_raw", x)
}

edgelist_raw.default <- function(x) {
    stop("Invalid input type. Please input file path as character or input data.frame directly.", call. = FALSE)
}

edgelist_raw.character <- function(x){
    if(isFALSE(file.exists(x))){
        stop("file not found")
    } else{
        df <- read.csv(x)
        edgelist_raw(df)
    }
}


edgelist_raw.data.frame <- function(x){
    #rest of code
}
```

You dont need to implement this now, but I would encourage to learn about generic functions and implement it in a later version
